version: "3"
services:
  mysql:
    build: mysql
    ports:
      - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
