-- MySQL Script generated by MySQL Workbench
-- Mon Nov  5 01:21:36 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sampledb
-- -----------------------------------------------------
-- サンプルDB
-- DROP SCHEMA IF EXISTS `sampledb` ;

-- -----------------------------------------------------
-- Schema sampledb
--
-- サンプルDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sampledb` DEFAULT CHARACTER SET utf8mb4 ;
USE `sampledb` ;

-- -----------------------------------------------------
-- Table `sampledb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sampledb`.`user` ;

CREATE TABLE IF NOT EXISTS `sampledb`.`user` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `organization` VARCHAR(100) NOT NULL,
  `note` VARCHAR(300) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sampledb`.`todo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sampledb`.`todo` ;

CREATE TABLE IF NOT EXISTS `sampledb`.`todo` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(300) NULL,
  `priority` INT NULL,
  PRIMARY KEY (`id`, `user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
