-- MySQL Script generated by MySQL Workbench
-- Fri May 24 16:45:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sampledb
-- -----------------------------------------------------
-- サンプルDB

-- -----------------------------------------------------
-- Schema sampledb
--
-- サンプルDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sampledb` DEFAULT CHARACTER SET utf8mb4 ;
USE `sampledb` ;

-- -----------------------------------------------------
-- Table `sampledb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sampledb`.`user` ;

CREATE TABLE IF NOT EXISTS `sampledb`.`user` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NULL,
  `email` VARCHAR(300) NULL,
  `password` VARCHAR(100) NULL,
  `phone` VARCHAR(100) NULL,
  `userStatus` INT NOT NULL DEFAULT 1 COMMENT '0:disable 1:enable',
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sampledb`.`todo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sampledb`.`todo` ;

CREATE TABLE IF NOT EXISTS `sampledb`.`todo` (
  `id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `title` VARCHAR(300) NOT NULL,
  `contents` TEXT NULL,
  `start` DATETIME NULL,
  `due` DATETIME NULL COMMENT '期日',
  `actualStart` DATETIME NULL,
  `actualEnd` DATETIME NULL,
  `status` INT NOT NULL DEFAULT 0 COMMENT '0:create 1:doing 2:done',
  `version` INT NOT NULL DEFAULT 0 COMMENT 'バージョン',
  PRIMARY KEY (`id`),
  INDEX `fk_todo_2_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_todo`
    FOREIGN KEY (`user_id`)
    REFERENCES `sampledb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
